version: '3.8'

services:
  hltv-discord-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hltv-discord-bridge
    restart: unless-stopped
    
    # Run as root to avoid permission issues with mounted files
    user: "0:0"
    
    # Memory limits to prevent excessive usage
    deploy:
      resources:
        limits:
          memory: 3G        # Maximum memory usage
        reservations:
          memory: 256M      # Reserved memory
    
    # Environment variables (most config is in config.xml)
    environment:
      # .NET Memory Optimizations
      - DOTNET_gcServer=1
      - DOTNET_gcConcurrent=1
      - DOTNET_GCLatencyLevel=1
      - DOTNET_EnableWriteXorExecute=0
      - DOTNET_ReadyToRun=1
      - DOTNET_TieredPGO=1
      - DOTNET_TC_QuickJitForLoops=1
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
    
    # Mount volumes for persistent data and configuration
    volumes:
      # Mount cache directory from host
      - ./cache:/app/cache
      # Mount config.xml from host (read-write for config updates)
      - ./config.xml:/app/config.xml
      # Mount logs directory
      - ./logs:/app/logs
      - ./icon.png:/app/icon.png
      - ./teamplaceholder.png:/app/teamplaceholder.png
    
    # Network configuration
    networks:
      - hltv-network
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
networks:
  hltv-network:
    driver: bridge
